steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_ARTIFACT_REGISTRY}/python-app:${BUILD_ID}', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_ARTIFACT_REGISTRY}/python-app:${BUILD_ID}']
- name: 'gcr.io/cloud-builders/gke-deploy'
  args:
  - run
  - --filename=k8s/
  - --image=${_ARTIFACT_REGISTRY}/python-app:${BUILD_ID}
  - --location=${_GCP_REGION}
  - --cluster=${_GKE_CLUSTER}
  - --namespace=${_KUBE_NAMESPACE}

substitutions:
  _ARTIFACT_REGISTRY: 'us-central1-docker.pkg.dev/${PROJECT_ID}/cicd-app'
  _GCP_REGION: 'us-central1'
  _GKE_CLUSTER: 'cicd-cluster'
  _KUBE_NAMESPACE: 'python-ci-cd'